name: Deploy App
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            
            - name: Install Nest
              run: npm i -g @nestjs/cli

            - name: Install dependencies
              run: npm install

            - name: Build Project
              run: npm run build

            - name: Login Dockerhub
              run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

            - name: Build docker image
              run: docker build -t augustod3v/api-ec2 .
            
            - name: Push image to Dockerhub
              run: docker push augustod3v/api-ec2 

    build-on-aws:
        runs-on: self-hosted
        steps: 
          - name: create folder test
            run: mkdir test-runner
